const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export { GET_EMPLOYEES_PENDING, GET_EMPLOYEES_SUCCESS, GET_EMPLOYEES_ERROR };
