export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';
export const DELETE_EMPLOYEE_PENDING = 'DELETE_EMPLOYEE_PENDING';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';
