export const POST_TIMESHEET_PENDING = 'POST_TIMESHEET_PENDING';
export const POST_TIMESHEET_SUCCESS = 'POST_TIMESHEET_SUCCESS';
export const POST_TIMESHEET_ERROR = 'POST_TIMESHEET_ERROR';
export const PUT_TIMESHEET_SUCCESS = 'PUT_TIMESHEET_SUCCESS';
export const PUT_TIMESHEET_PENDING = 'PUT_TIMESHEET_PENDING';
export const PUT_TIMESHEET_ERROR = 'PUT_TIMESHEET_ERROR';
