export const GET_SUPER_ADMINS_PENDING = 'GET_SUPER_ADMINS_PENDING';
export const GET_SUPER_ADMINS_SUCCESS = 'GET_SUPER_ADMINS_SUCCESS';
export const GET_SUPER_ADMINS_ERROR = 'GET_SUPER_ADMINS_ERROR';
