const GET_ENTITY_PENDING = 'GET_ENTITY_PENDING';
const GET_ENTITY_SUCCESS = 'GET_ENTITY_SUCCESS';
const GET_ENTITY_ERROR = 'GET_ENTITY_ERROR';

const DELETE_ENTITY_PENDING = 'DELETE_ENTITY_PENDING';
const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
const DELETE_ENTITY_ERROR = 'DELETE_ENTITY_ERROR';

const ADD_ENTITY_PENDING = 'ADD_ENTITY_PENDING';
const ADD_ENTITY_SUCCESS = 'ADD_ENTITY_SUCCESS';
const ADD_ENTITY_ERROR = 'ADD_ENTITY_ERROR';

const UPDATE_ENTITY_PENDING = 'UPDATE_ENTITY_PENDING';
const UPDATE_ENTITY_SUCCESS = 'UPDATE_ENTITY_SUCCESS';
const UPDATE_ENTITY_ERROR = 'UPDATE_ENTITY_ERROR';

export {
  GET_ENTITY_PENDING,
  GET_ENTITY_SUCCESS,
  GET_ENTITY_ERROR,
  DELETE_ENTITY_PENDING,
  DELETE_ENTITY_SUCCESS,
  DELETE_ENTITY_ERROR,
  ADD_ENTITY_PENDING,
  ADD_ENTITY_SUCCESS,
  ADD_ENTITY_ERROR,
  UPDATE_ENTITY_PENDING,
  UPDATE_ENTITY_SUCCESS,
  UPDATE_ENTITY_ERROR
};
