const GET_ENTITY_PENDING = 'GET_ENTITY_PENDING';
const GET_ENTITY_SUCCESS = 'GET_ENTITY_SUCCESS';
const GET_ENTITY_REJECTED = 'GET_ENTITY_REJECTED';

const DELETE_ENTITY_PENDING = 'DELETE_ENTITY_PENDING';
const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
const DELETE_ENTITY_REJECTED = 'DELETE_ENTITY_REJECTED';

const ADD_ENTITY_PENDING = 'ADD_ENTITY_PENDING';
const ADD_ENTITY_SUCCESS = 'ADD_ENTITY_SUCCESS';
const ADD_ENTITY_REJECTED = 'ADD_ENTITY_REJECTED';

const TOGGLE_ENTITY_PENDING = 'TOGGLE_ENTITY_PENDING';
const TOGGLE_ENTITY_SUCCESS = 'TOGGLE_ENTITY_SUCCESS';
const TOGGLE_ENTITY_REJECTED = 'TOGGLE_ENTITY_REJECTED';

export {
  GET_ENTITY_PENDING,
  GET_ENTITY_SUCCESS,
  GET_ENTITY_REJECTED,
  DELETE_ENTITY_PENDING,
  DELETE_ENTITY_SUCCESS,
  DELETE_ENTITY_REJECTED,
  ADD_ENTITY_PENDING,
  ADD_ENTITY_SUCCESS,
  ADD_ENTITY_REJECTED,
  TOGGLE_ENTITY_PENDING,
  TOGGLE_ENTITY_SUCCESS,
  TOGGLE_ENTITY_REJECTED
};
