const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';

const DELETE_PROJECT_PENDING = 'DELETE_PROJECT_PENDING';
const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';

const POST_PROJECT_PENDING = 'POST_PROJECT_PENDING';
const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS';
const POST_PROJECT_ERROR = 'POST_PROJECT_ERROR';

const PUT_PROJECT_PENDING = 'PUT_PROJECT_PENDING';
const PUT_PROJECT_SUCCESS = 'PUT_PROJECT_SUCCESS';
const PUT_PROJECT_ERROR = 'PUT_PROJECT_ERROR';

export {
  GET_PROJECTS_PENDING,
  GET_PROJECTS_SUCCESS,
  GET_PROJECTS_ERROR,
  DELETE_PROJECT_PENDING,
  DELETE_PROJECT_SUCCESS,
  DELETE_PROJECT_ERROR,
  POST_PROJECT_PENDING,
  POST_PROJECT_SUCCESS,
  POST_PROJECT_ERROR,
  PUT_PROJECT_PENDING,
  PUT_PROJECT_SUCCESS,
  PUT_PROJECT_ERROR
};
